### ISSUE TITLE
Saving included files doesn't compile main.scss + it compiles itself

### ISSUE THREAD

**Issue by artipixel** [jasonsanjose/brackets-sass#68]
Hi,
When I'm trying to save some included sass files, it compiles itself, although I specifically disabled this option. additionally, it doesn't compile the main file - main.scss. I need to save 2 files very time I make a change, and I get weird errors as well, like this one - 
![image](https://cloud.githubusercontent.com/assets/6322237/5300677/d3efe600-7bda-11e4-8c63-19fffdcf05e5.png)
Alltogh there is nothing wrong with that file. 
When I'm trying to un-include this file it gives me the same error with the next file.

Also, It's still generating maps - and I specifically disabled it too.
The reason - it calls the full path instead the relative, I'm developing it on my computer and it's not very good to have a path like `F:/project/project_name` ...
This is my `.json` file:
```
{
    "path": {
        "media/scss/main.scss": {
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../css/",
                "includePaths": [
                    "media/scss/"
                ],
                "imagePath": null,
                "sourceComments": "none",
                "outputStyle": "nested",
                "media/scss/*.scss": {
                    "sass.enabled": false
                }
            }
        }
    }
}
```

and my folder tree:

```
│   .brackets.json
│   .htaccess
│   404.html
│   apple-touch-icon-precomposed.png
│   crossdomain.xml
│   favicon.ico
│   humans.txt
│   index.html
│   robots.txt
─media
 ├───css
 │       main.css
 │       main.css.map
 │
 └───scss
     │   main.scss
     │
     ├───core
     │       base.css
     │       base.css.map
     │       base.scss
     │       directional.css
     │       directional.css.map
     │       directional.scss
     │       functions.css
     │       functions.css.map
     │       functions.scss
     │       typography.scss
     │       vars.css
     │       vars.css.map
     │       vars.scss
     │
     ├───normalize
     │       normalize.scss
     │
     ├───pages
     │       common.css
     │       common.css.map
     │       common.scss
     │       painting.scss
     │       school_home.scss
     │
     └───responsive
             grid.css
             grid.css.map
             grid.scss
```

This is my main.scss file:

```
@charset "UTF-8";
/*vars*/
@import "core/vars"; 
/*functions*/
@import "core/functions";
/*languages*/
@import "core/directional";
/*normalize*/
@import "normalize/normalize";
/*typography*/
@import "core/typography";
/*base*/ 
@import "core/base";
/*common*/
@import "pages/common";
/*painting page*/
@import "pages/painting"; 
/*home page*/
@import "pages/school_home"; 
/*responsive*/
@import "responsive/grid"; 
```

The really weird thing is that it saves the file at `../css` folder, so the `.json` file configuration does work.
Help, please? :(

**Comment by Dexyne** [comment]
I'm having a similar issue, when saving my file with import rule it's not working correctly and see the same message as the first post.

- I try the solution given by @cosmefae because compiling with another name is not working
- Using **app.sass** not working too, only **SCSS** works for me.
- I try to include in .brackets.json something like this ``` "partials/*.sass": { "sass.enabled": false } ``` but it compile in the same directory and not include anything

So actually all my files inside ```partials/``` use the _name syntax (ex: _component.sass).

Actually my .brackets.json file include this:
```
"app.scss": {
    "sass.enabled": true,
    "sass.options": {
        "outputDir": "../css/"
    }
}
```
and my tree looks like this:
```
css/
    app.css
    app.css.map
sass/
    partials/
        _partial_1.sass
        _partial_2.sass
    app.scss
```

**Comment by jasonsanjose** [comment]
@artipixel I think your `.brackets.json` file is wrong. You're specifying a path `media/scss/*.scss` inside another path `media/scss/main.scss`. This is invalid. I think what you want is below:

```
{
    "path": {
        "media/scss/main.scss": {
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../css/",
                "includePaths": [
                    "media/scss/"
                ],
                "imagePath": null,
                "sourceComments": "none",
                "outputStyle": "nested"
            }
        },
        "media/scss/*.scss": {
            "sass.enabled": false
        }
    }
}
```

However, in addition to the `.brackets.json` problem, there is a bug here even with the correct JSON where the main file doesn't get compiled. I'll have a fix soon.

**Comment by jasonsanjose** [comment]
Fixed in #78, version 1.0.3-80.

Here's an alternative `.brackets.json` that disabled SASS compiling by default, then enables it just for your root level file:

```
{
    "sass.enabled": false,
    "path": {
        "media/scss/main.scss": {
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../css/",
                "includePaths": [
                    "media/scss/"
                ],
                "imagePath": null,
                "sourceComments": "none",
                "outputStyle": "nested"
            }
        }
    }
}
```

**Comment by Belkar** [comment]
The last update just made it worse for me. I tried the config you provided here: https://github.com/jasonsanjose/brackets-sass/issues/68#issuecomment-70479171 but I can't get it to work. (I changed the folder names but everything else is the same)

My folders look like the following:
```
root
|- css // Output folder of SCSS
|- js
|- ...
|- scss
  |- app.scss
  |- imports
    |- main.scss
    |- layout.scss
    |- ...
```
My app.scss just consists of @imports but changing a file in the subfolder "imports" doesn't cause app.scss to recompile.

**Comment by jasonsanjose** [comment]
@Belkar that sample was just for @artipixel. Looking at your example, you'll want a `.brackets.json` file that looks like this

```
scss/app.scss
-------------------
@import "main"
@import "layout"
...

.brackets.json
------------------
{
    "sass.enabled": false,
    "path": {
        "scss/app.scss": {
            "sass.enabled": true,
            "sass.options": {
                "outputDir": "../css/",
                "includePaths": ["imports/"],
                "imagePath": null,
                "sourceComments": "none",
                "outputStyle": "nested"
            }
        }
    }
}
```

**Comment by Belkar** [comment]
Thanks for the fast reply but i can't get it to work.
I'm on Windows using your latest version (1.0.4-83)

Saving app.scss works but changing something in imports/*.scss doesn't cause it to recompile

**Comment by artipixel** [comment]
Also thanks,
I will test it as soon as I can,
The website is in production and I had to use an external compiler :(

**Comment by panablue** [comment]
I continue to have this issue: **saving a partial/imported SCSS file doesn't trigger a recompile of the main SCSS file and update of the live preview**.

Here's my .brackets.json:
{
	"sass.enabled": false,
    "path": {
        "scss/master.scss": {
            "sass.enabled": true,
            "sass.options": {
                "output": "../styles.css",
                "includePaths": [],
                "sourceComments": "none",
                "outputStyle": "compressed"
            }
        }
    }
}

**Comment by jasonsanjose** [comment]
Reopened. @panablue can you try this dev build https://github.com/jasonsanjose/brackets-sass/releases/tag/2.0.1-105 and see if it fixes your issue with partials not recompiling the main input?

**Comment by panablue** [comment]
It appears to be working - and updating without saving is extra awesome.

Maybe not even worth addressing, but I noticed a small anomaly that occurs **when making edits between 2 open partial files**:

Changes to either file updates the live preview as expected, but ***saving* partial A updates the live preview to show the *last-saved version* of partial B**. (However **saving partial B then re-updates the live preview with the changes since the last save**.)

Thank you for taking the time on this.

(I'm on Windows 7.)

**Comment by jasonsanjose** [comment]
@panablue thanks for the feedback. 

>Maybe not even worth addressing, but I noticed a small anomaly that occurs when making edits between 2 open partial files:

>Changes to either file updates the live preview as expected, but saving partial A updates the live preview to show the last-saved version of partial B. (However saving partial B then re-updates the live preview with the changes since the last save.)

Can you file this as a separate bug? Pretty sure that's fixable. Thanks again.

**Comment by jasonsanjose** [comment]
Fixed in #100. Closing

**Comment by HumidBrains** [comment]
I get the same problem on Mac as @panablue had on Windows. No live preview and no compiling as soon as I import partials into the app.scss file. Commenting out the imports of partials instantly shows live preview and compiling with file mapping works fine, so it's the imports that breaks it for me. I'm on Yosemite and use brackets-sass v 2.0.1-109. My setup below...

root
|- css // Output folder of SCSS
    |- app.css
    |- app.css.map
|- scss
    |- app.scss
    |- imports
        |- _variables.scss
        |- _graphs.scss
        |- ...


scss/app.scss
-------------------
@import "variables"
@import "graphs"
...

.brackets.json
------------------
{
    "sass.enabled": false,
    "path": {
          "scss/app.scss": {
                "sass.enabled": true,
                "sass.options": {
                    "outputDir": "../css/",
                    "includePaths": ["imports/"],
                    "imagePath": null,
                    "sourceComments": "none",
                    "outputStyle": "nested"
}

**Comment by TsuNut** [comment]
Saving a partial/imported SCSS file doesn't trigger a recompile of the main SCSS file for me neither. :(

**Comment by jnaklaas** [comment]
Hi
I'm still having this issue, as this post has been around for a while: is there any solution for this?

Sass only compiles when updating the main scss file, not when saving an @import scss file.

**Comment by MartinGeldart** [comment]
Try adding this commented-out line to the top of all of your _partial files:

`// main: main.scss`

This tells SASS to compile your main SCSS file when saving a partial. Obviously, change `main.scss` to whichever filename you're using as your main.
